project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - FinalProject.qmd
    - magic_cube_generation.qmd

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Chiefs Data Project
        href: FinalProject.qmd
      - text: Magic Cube Generation
        href: magic_cube_generation.qmd
      
format:
  html:
    backgroundcolor: "#FFFFFF"
    mainfont: "helvetica"
    theme: [cosmo, styles.scss]

